language: go
sudo: false
go: 1.6.2
os: osx
notifications:
  email: false
branches:
  except:
    - gh-pages
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: dist/chrome-bookmarks.alfredworkflow
  skip_cleanup: true
  on:
    tags: true
before_install:
  - brew update
  - brew install glide
  - glide --version
install:
  - make deps
script:
  - make clean
  - make lint
  - make coveralls
  - make workflow
