---
- name: "chrome"
  fullName: "com.google.Chrome"
  description: "Google Chrome"
  path: "~/Library/Application Support/Google/Chrome"
  iconUrl: "chrome.png"
  profileName: "Default"

- name: "canary"
  fullName: "com.google.Chrome.canary"
  description: "Google Chrome Canary"
  path: "~/Library/Application Support/Google/Chrome Canary"
  iconUrl: "canary.png"
  profileName: "Default"

- name: "chromium"
  fullName: "org.chromium.Chromium"
  description: "Chromium"
  path: "~/Library/Application Support/Chromium"
  iconUrl: "chromium.png"
  profileName: "Default"

- name: "edge"
  fullName: "com.microsoft.edgemac"
  description: "Microsoft Edge"
  path: "~/Library/Application Support/Microsoft Edge"
  iconUrl: "edge.png"
  profileName: "Default"

- name: "edge-canary"
  fullName: "com.microsoft.edgemac.Canary"
  description: "Microsoft Edge Canary"
  path: "~/Library/Application Support/Microsoft Edge Canary"
  iconUrl: "edge-canary.png"
  profileName: "Default"

- name: "vivaldi"
  fullName: "com.vivaldi.Vivaldi"
  description: "Vivaldi"
  path: "~/Library/Application Support/Vivaldi"
  iconUrl: "vivaldi.png"
  profileName: "Default"

