---
chrome:
  bookmarkListId: "5f62cd88-0737-48db-a56a-c28761a4fcab"
  bookmarkOpenId: "f66a1d83-c6fe-409b-b3bd-d8ccce841491"
  profileListId: "5ce75d7f-c847-4000-a386-3e460dab8f9b"
  profileSetId: "980c9bc1-366c-4c72-bea7-c1ec7ba6ed6d"

canary:
  bookmarkListId: "51ad66cf-5391-4b3d-98eb-9c96711b4dd3"
  bookmarkOpenId: "840775c1-f247-4b1b-8a1e-5679e96b52cf"
  profileListId: "52effb47-f969-4fe6-91ed-7ae255c79786"
  profileSetId: "9dff45f0-2c9e-4c12-b65d-4a70427682fe"

chromium:
  bookmarkListId: "5c5a3de8-474a-42bf-99f6-c61f793a6625"
  bookmarkOpenId: "fe18d1b8-0883-4dae-b463-48b6c86b89b4"
  profileListId: "0dbb6f03-744b-4821-8483-d3e773df15d6"
  profileSetId: "c7b2c7e1-29f0-4b00-84d5-7c3a8bf69549"

edge:
  bookmarkListId: "bba7dce5-3ab8-4d6b-b60b-0a657244b9e0"
  bookmarkOpenId: "acc08389-2a8d-4943-b224-4cfb06722601"
  profileListId: "fe077da3-9be5-42f0-bc42-dff10527b4a1"
  profileSetId: "d049ea91-55c4-4bb0-97b0-f6512c7c6842"

edge-canary:
  bookmarkListId: "d8ea0a40-6493-4e42-af3b-3630ec9eba2d"
  bookmarkOpenId: "cd405773-829b-4eff-bb1f-a8eb2d613bc9"
  profileListId: "f5ca2278-6a2b-48fa-ae9c-d20b76eceab2"
  profileSetId: "107896de-aa3a-45f2-833e-c4c7d0421c13"

vivaldi:
  bookmarkListId: "caa9ecf5-d269-4757-b555-61b2d6dee497"
  bookmarkOpenId: "05008a94-3fd7-44d4-aa10-b0f2a495d360"
  profileListId: "093cb3e1-761a-4f34-83f6-36507c8c6eff"
  profileSetId: "0d4fbc34-60ed-4223-98c9-5a93a103aa5c"
